# Generated by Django 3.2.22 on 2023-10-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdl_portfolio', '0003_auto_20231008_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcareerinfo',
            name='skills',
            field=models.JSONField(default=dict),
        ),
    ]
