# Generated by Django 3.2.22 on 2023-10-08 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kdl_portfolio', '0004_alter_studentcareerinfo_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcareerinfo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='studentcareerinfo',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='project',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentcareerinfo',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
