# Generated by Django 3.2.22 on 2023-10-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdl_portfolio', '0005_auto_20231008_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='youtube_url',
            field=models.URLField(null=True),
        ),
    ]
