# Generated by Django 3.2.22 on 2023-10-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdl_portfolio', '0006_project_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(null=True),
        ),
    ]
